### ISSUE TITLE
save/load model?

### ISSUE THREAD

**Issue by AniSkywalker** [Savvysherpa/slda#4]
How can we load/save the model (similar to Gensim LDA library)?

**Comment by bearnshaw** [comment]
Unfortunately, the current models do not include a convenient API for saving and loading models.  However, you only need `alpha`, `beta` and `phi` from a trained model in order to infer the topics of documents, so you could save those after training (e.g. dump pickle file to disk), and then in future sessions you could load them again and set them on a newly instantiated model.  Then you can just use the `transform` method of the model.

**Comment by AniSkywalker** [comment]
Thank you very much. 
I will close the issue.

I have one more question: if I call model.fit() with mini-batches of the entire dataset, will it produce the same as training with the entire dataset?
